---
- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "{{ key_file }}"
    type: rsa
    size: 2048
    force: true
  register: ssh_keypair

- name: Create EC2 Key Pair
  amazon.aws.ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ key_name }}"
    key_material: "{{ ssh_keypair.public_key }}"
    region: "{{ aws_region }}"
    force: true
  register: ec2_keypair