---
# Azure Packages Installation
- name: Generate SSH key pair
  community.crypto.openssh_keypair:
    path: "{{ ssh_role_dir }}/{{ ssh_key_name }}"
    force: true  # rewrites SSH key if already present