---
- name: Generate SSH key pair
  community.crypto.openssh_keypair:
    type: rsa
    size: 2048
    path: "{{ ssh_role_dir }}/{{ ssh_key_name }}"
    force: true  # rewrites SSH key if already present