---
- name: Build Instance
  hosts: localhost
  vars_files:
    - vars/main.yml

  tasks:
    - name: create a new EC2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: "{{ ec2_key_name }}"
        file_name: "{{ ssh_role_dir }}/{{ ec2_key_name }}"
        #no_log: true
      register: aws_ec2_key_pair