---
- name: Build Instance
  hosts: localhost
  vars_files:
    - vars/main.yml

  tasks:

    - name: Create an EC2 key
      amazon.aws.ec2_key:
        name: "{{ ec2_key_name }}"
        region: "{{ aws_region }}"
        access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: aws_ec2_key_pair

    - name: save private key
      copy:
        content: "{{ aws_ec2_key_pair }}" 
        dest: "{{ ssh_role_dir }}/{{ ec2_key_name }}" 
        mode: 0600
      when: aws_ec2_key_pair.changed