---

- name: AWS Pre-Req Install
  ansible.builtin.include_tasks: "pre-req-install/tasks/aws.yml"
  when: foundation == 'aws'

- name: Azure Pre-Req Install
  ansible.builtin.include_tasks: "pre-req-install/tasks/azure.yml"
  when: foundation == 'azure'

- name: Libvrt Pre-Req Install
  ansible.builtin.include_tasks: "pre-req-install/tasks/libvrt.yml"
  when: foundation == 'libvrt'

- name: GCP AWS Pre-Req Install
  ansible.builtin.include_tasks: "pre-req-install/tasks/gcp.yml"
  when: foundation == 'gcp'