---

- name: AWS Pre-Req Install
  ansible.builtin.include_tasks: "aws.yaml"
  when: foundation == 'aws'

- name: Azure Pre-Req Install
  ansible.builtin.include_tasks: "azure.yaml"
  when: foundation == 'azure'

- name: Libvrt Pre-Req Install
  ansible.builtin.include_tasks: "libvrt.yaml"
  when: foundation == 'libvrt'

- name: GCP AWS Pre-Req Install
  ansible.builtin.include_tasks: "gcp.yaml"
  when: foundation == 'gcp'