---

- name: AWS Pre-Req Install
  ansible.builtin.include_tasks: "aws.yml"
  when: foundation == 'aws'

- name: Azure Pre-Req Install
  ansible.builtin.include_tasks: "azure.yml"
  when: foundation == 'azure'

- name: Libvrt Pre-Req Install
  ansible.builtin.include_tasks: "libvrt.yml"
  when: foundation == 'libvrt'

- name: GCP AWS Pre-Req Install
  ansible.builtin.include_tasks: "gcp.yml"
  when: foundation == 'gcp'