---
- name: Build Instance  
  hosts: localhost
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: /home/oezeakac/labs/Ansible/cornerstone-collection/cornerstone/roles/Cornerstone
